// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByErMcjyQ0400jFf2ErBSjgPRtRWJzfOo',
    appId: '1:873476775920:web:d324640531873589578735',
    messagingSenderId: '873476775920',
    projectId: 'sowjanyathota',
    authDomain: 'sowjanyathota.firebaseapp.com',
    storageBucket: 'sowjanyathota.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHxqeU8MMJHkQTbxneAc1TAZXdm7CIwJw',
    appId: '1:873476775920:android:13c18f84490476bc578735',
    messagingSenderId: '873476775920',
    projectId: 'sowjanyathota',
    storageBucket: 'sowjanyathota.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Np6fdoQBnGK-_oF6epmlZAkY4N7lylY',
    appId: '1:873476775920:ios:50cd1a27da72af6f578735',
    messagingSenderId: '873476775920',
    projectId: 'sowjanyathota',
    storageBucket: 'sowjanyathota.appspot.com',
    iosClientId: '873476775920-rtl3ctq0lic2h9mmkvsidjetct2aoflb.apps.googleusercontent.com',
    iosBundleId: 'com.example.andriod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Np6fdoQBnGK-_oF6epmlZAkY4N7lylY',
    appId: '1:873476775920:ios:9417b71c3f68e491578735',
    messagingSenderId: '873476775920',
    projectId: 'sowjanyathota',
    storageBucket: 'sowjanyathota.appspot.com',
    iosClientId: '873476775920-2eq47lvgie91kfbe481aljq02tnqeugm.apps.googleusercontent.com',
    iosBundleId: 'com.example.andriod.RunnerTests',
  );
}
